// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://btoaiqpvcfvwoydfndiu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ0b2FpcXB2Y2Z2d295ZGZuZGl1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTg5NTQ4MTYsImV4cCI6MjA3NDUzMDgxNn0.oaKJ-FG7UbPnDwIW9lyP-E48HcsPRjWnPou-4C5FbsU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});